---
version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - "gosec"
  disable:
    - "errcheck"
  settings:
    gosec:
      includes:
        - G501 # Import blocklist: crypto/md5
        - G502 # Import blocklist: crypto/des
        - G503 # Import blocklist: crypto/rc4
        - G504 # Import blocklist: net/http/cgi
        - G505 # Import blocklist: crypto/sha1
        - G506 # Import blocklist: golang.org/x/crypto/md4
        - G507 # Import blocklist: golang.org/x/crypto/ripemd160

