name: Runs Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - stable
          - 1.21.x
          - 1.20.x
          - 1.19.x
          - 1.18.x
          - 1.17.x
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go test -v -vet=all -tags CI -race ./...
      env:
        GOPATH: /home/runner/go
